### ISSUE TITLE
Can't change conda environment, setting RETICULATE_PYTON= in .Rprofile or .Renviron doesn't resolve

### ISSUE THREAD

**Issue by lyndbacon** [rstudio/reticulate#1243]
I am unable to set a conda environment using reticulate in an R session, or to set it in .Rprofile or in .Renviron.   I was able to do the latter using reticulate 1.22. 

Ubuntu Linux 20.04 LTS, R 4.2.1, reticulate 4.2.1.

Loading reticulate in R session w/o setting RETICULATE_PYTHON path in .Rprofile or in .Renviron:

```
> py_discover_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
pythonhome:     //usr://usr
version:        3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
numpy:          /home/lynd/.local/lib/python3.8/site-packages/numpy
numpy_version:  1.22.3

python versions found: 
 /usr/bin/python3
 /home/lynd/anaconda3/bin/python
 /home/lynd/.virtualenvs/bayespy/bin/python
 /home/lynd/.virtualenvs/powerlaws/bin/python
 /home/lynd/.virtualenvs/pystan3/bin/python
 /home/lynd/.virtualenvs/topicmap/bin/python
 /home/lynd/anaconda3/envs/aif360/bin/python
 /home/lynd/anaconda3/envs/causal/bin/python
 /home/lynd/anaconda3/envs/doe/bin/python
 /home/lynd/anaconda3/envs/gpflow2/bin/python
 /home/lynd/anaconda3/envs/kivy/bin/python
 /home/lynd/anaconda3/envs/openCV/bin/python
 /home/lynd/anaconda3/envs/openDP/bin/python
 /home/lynd/anaconda3/envs/py310/bin/python
 /home/lynd/anaconda3/envs/py38/bin/python
 /home/lynd/anaconda3/envs/pytorch/bin/python
 /home/lynd/anaconda3/envs/rare-events/bin/python
 /home/lynd/anaconda3/envs/tfpy38/bin/python
 /home/lynd/anaconda3/envs/tfpy39/bin/python
 /home/lynd/anaconda3/envs/yellowbrick/bin/python
> 
```
Attempting to change to a conda env.:

```
> use_condaenv('tfpy39')
/tmp/RtmpIySeeV/file10302181dd816.sh: 5: /home/lynd/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) :
  running command ''/bin/sh' /tmp/RtmpIySeeV/file10302181dd816.sh' had status 2
> 
```

With RETICULATE_PATH set in .Rprofile:

```
lynd@xxx:~$ cat .Rprofile
# Sys.setenv(RETICULATE_PYTHON='/home/lynd/anaconda3/envs/tfpy38/bin/python')
Sys.setenv(RETICULATE_PYTHON='/home/lynd/anaconda3/envs/tfpy39/bin/python')
# Sys.setenv(RETICULATE_PYTHON='/home/lynd/anaconda3/envs/py38/bin/python')
options(expressions = 5e5)
```
Then in R:
```
> library(reticulate)
> py_config()
/tmp/Rtmp3dZi0c/file1038a482cd5cb.sh: 5: /home/lynd/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) :
  running command ''/bin/sh' /tmp/Rtmp3dZi0c/file1038a482cd5cb.sh' had status 2
> 
```
I had installed reticulate as su. I removed it and installed it as myself as user, and got the same results as above.
I get the same results as above if I set RETICULATE_PYTHON in .Renviron.
Removing and reinstalling reticulate makes no difference.
launching R from a conda env produces the error message immediately above. 
I believe the  `Error in Sys.setenv(PATH = new_path) : wrong length for argument` message has occurred recently with special configurations.  A permissions problem? 

Suggestions will be appreciated!

**Comment by t-kalinowski** [comment]
Hi, thanks for reporting. I tried locally but can't reproduce the error on my machine.

What output do you get from running this?

```r
envir::import_from(reticulate, "**")

python <- "/home/lynd/anaconda3/envs/tfpy39/bin/python"
conda_info <- get_python_conda_info(python)

new_path <- conda_run2(
  "python",
  c("-c", shQuote("import os; print(os.environ['PATH'])")),
  conda = conda_info$conda,
  envname = conda_info$root,
  intern = TRUE
)

print(new_path)
```

**Comment by lyndbacon** [comment]
Hi.  Thanks.  Here's what I get:
```
> envir::import_from(reticulate, "**")
Error in loadNamespace(x) : there is no package called ‘envir’
> 
> python <- "/home/lynd/anaconda3/envs/tfpy39/bin/python"
> conda_info <- get_python_conda_info(python)
Error in get_python_conda_info(python) : 
  could not find function "get_python_conda_info"
> 
> new_path <- conda_run2(
+   "python",
+   c("-c", shQuote("import os; print(os.environ['PATH'])")),
+   conda = conda_info$conda,
+   envname = conda_info$root,
+   intern = TRUE
+ )
Error in conda_run2("python", c("-c", shQuote("import os; print(os.environ['PATH'])")),  : 
  could not find function "conda_run2"
> 
> print(new_path)
Error in print(new_path) : object 'new_path' not found
```

**Comment by t-kalinowski** [comment]
what is `conda_info("/home/lynd/anaconda3/envs/tfpy39/bin/python")`?

**Comment by lyndbacon** [comment]
In a new R session from the cli:

```
> conda_info('/home/lynd/anaconda3/envs/tfpy39/bin/python')
Error in conda_info("/home/lynd/anaconda3/envs/tfpy39/bin/python") : 
  could not find function "conda_info"
> library(reticulate)
> conda_info('/home/lynd/anaconda3/envs/tfpy39/bin/python')
Error in conda_info("/home/lynd/anaconda3/envs/tfpy39/bin/python") : 
  could not find function "conda_info"
> 
```

**Comment by t-kalinowski** [comment]
`reticulate:::conda_info()`

**Comment by lyndbacon** [comment]
```
> reticulate:::conda_info('/home/lynd/anaconda3/envs/tfpy39/bin/python')
/home/lynd/anaconda3/envs/tfpy39/bin/python3.9: can't open file '/home/lynd/info': [Errno 2] No such file or directory
Error: lexical error: invalid char in json text.
                                       NA
                     (right here) ------^
In addition: Warning messages:
1: In conda_binary(conda) :
  Supplied path is not a conda binary: ‘/home/lynd/anaconda3/envs/tfpy39/bin/python3.9’
2: In system2(conda, c("info", "--json"), stdout = TRUE) :
  running command ''/home/lynd/anaconda3/envs/tfpy39/bin/python3.9' info --json' had status 2
> 
```

**Comment by lyndbacon** [comment]
This is the result of trying to set RETICULATE_PATH in an R session.  It wasn't set in either .Rprofile or in .Renviron.
A permissions problem, perhaps?

```
> Sys.setenv(RETICULATE_PYTHON='/home/lynd/anaconda3/envs/tfpy39/bin/python')
> library(reticulate)
> py_config()
/tmp/RtmpfL1NY8/file155ab669678ea9.sh: 5: /home/lynd/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) :
  running command ''/bin/sh' /tmp/RtmpfL1NY8/file155ab669678ea9.sh' had status 2
```

**Comment by kevinushey** [comment]
@t-kalinowski, do you have any ideas? I feel like `conda run` is causing more problems that it's solving as I think this has popped up on a couple of other issues as well.

**Comment by lyndbacon** [comment]
Hm. No new ideas so far.  I've been groping through stuff that's online seeking clues.   

bash might be better, at least for me.  ;-)  I don't know how commonly used the other shells are.   echo $0 can tell what shell is in use.

I'm currently using reticulate, tensorflow, keras to teach an R based course about ML + AI. I hesitate to tear everything apart lest I end up with nothing that works for a bit going forward.  For what it's worth, all my conda environments work as they should when I run Python.

**Comment by lyndbacon** [comment]
I note that if I run sh rather than bash, `conda activate` doesn't work for me:
```
lynd@zdog:~$ /bin/sh
$ conda activate tfpy39

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

**Comment by t-kalinowski** [comment]
What is `condo_info` after running this snippet? 
```r
python <- "/home/lynd/anaconda3/envs/tfpy39/bin/python"
conda_info <- get_python_conda_info(python)
conda_info
```

**Comment by lyndbacon** [comment]
```
> python <-'/home/lynd/anaconda3/envs/tfpy39/bin/python'
> conda_info <- reticulate:::get_python_conda_info(python)
> conda_info
$conda
[1] "/home/lynd/anaconda3/bin/conda"

$root
[1] "/home/lynd/anaconda3/envs/tfpy39"

```

**Comment by t-kalinowski** [comment]
@lyndbacon Can you share how you created the conda env? Ideally what commands you ran in your shell so I can recreate it, or the output of `conda list` from a shell with the conda environment activated. 

Is there perhaps a version of Conda-built R also in the conda environment that is conflicting with the CRAN-built R you're running reticulate from? 

I pushed a small patch which may help, can you please try it out and report back?
```r
remotes::install_github("rstudio/reticulate@fix/conda-activate")
```

**Comment by lyndbacon** [comment]
Thanks.  Here's output from reticulate:::conda_list() :

```
> reticulate:::conda_list()
          name                                           python
1         base                  /home/lynd/anaconda3/bin/python
2       aif360      /home/lynd/anaconda3/envs/aif360/bin/python
3       causal      /home/lynd/anaconda3/envs/causal/bin/python
4          doe         /home/lynd/anaconda3/envs/doe/bin/python
5      gpflow2     /home/lynd/anaconda3/envs/gpflow2/bin/python
6         kivy        /home/lynd/anaconda3/envs/kivy/bin/python
7       openCV      /home/lynd/anaconda3/envs/openCV/bin/python
8       openDP      /home/lynd/anaconda3/envs/openDP/bin/python
9        py310       /home/lynd/anaconda3/envs/py310/bin/python
10        py38        /home/lynd/anaconda3/envs/py38/bin/python
11     pytorch     /home/lynd/anaconda3/envs/pytorch/bin/python
12 rare-events /home/lynd/anaconda3/envs/rare-events/bin/python
13      tfpy38      /home/lynd/anaconda3/envs/tfpy38/bin/python
14      tfpy39      /home/lynd/anaconda3/envs/tfpy39/bin/python
15 yellowbrick /home/lynd/anaconda3/envs/yellowbrick/bin/python
```
The above is without anything set for RETICULATE_PYTHON in either .Rprofile or in .Renviron, and having launched R from my home directory w/o any conda env activate.   Trying to use use_condaenv() to switch to a different conda env results in:

```
> use_condaenv('tfpy38')
ERROR: The requested version of Python
('/home/lynd/anaconda3/envs/tfpy38/bin/python') cannot be used, as
another version of Python ('/usr/bin/python3') has already been
initialized. Please restart the R session if you need to attach
reticulate to a different version of Python.
Error in use_python(python, required = required) : 
  failed to initialize requested version of Python
```
The above message happens regardless of the conda env I try to activate.
Launching R after having activated the conda env tfpy39:

```
> library(reticulate)
> use_condaenv('tfpy39')
/tmp/Rtmp64bdGI/file1f610840276c5f.sh: 5: /home/lynd/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) :
  running command ''/bin/sh' /tmp/Rtmp64bdGI/file1f610840276c5f.sh' had status 2
> 
```
My conda envs have been created using the usual CLI statement, e.g.

```
lynd@zdog:~$ conda create -n testPy python=3.10

```
Having newly created the conda env testPy, and trying to switch to it in R:

```> use_condaenv('testPy')
ERROR: The requested version of Python
('/home/lynd/anaconda3/envs/testPy/bin/python') cannot be used, as
another version of Python ('/usr/bin/python3') has already been
initialized. Please restart the R session if you need to attach
reticulate to a different version of Python.
Error in use_python(python, required = required) : 
  failed to initialize requested version of Python
```

I'll give your patch a try.  I've been thinking I might try hard coding the path that conda_run2_nix returns from in conda.R

**Comment by t-kalinowski** [comment]
hi @lyndbacon,

I should have been more clear, I meant, what is the output of `conda list` from the terminal (bash or zsh), not R.

Do you know why reticulate is binding to `/usr/bin/python` for you? Do you perhaps have something in your .Rprofile that is causing reticulate to activate the environment? 

Unfortunately this is tricky issue to debug because I can't reproduce it locally. For example, on my M1 Mac this sequence of commands works without issue:

In terminal (zsh), install conda
```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh
chmod +x Miniconda3-latest-MacOSX-arm64.sh 
./Miniconda3-latest-MacOSX-arm64.sh 
```
In terminal, create the condaenv
```
. miniconda3/bin/activate 
conda create -n testPy python=3.10
```

Then from Rstudio R console in a fresh R session, I can bind to the environment without issues, (both the current main branch of reticulate, and the branch with my patch):
```> reticulate::use_condaenv("testPy")
> reticulate::py_config()
python:         /Users/tomasz/miniconda3/envs/testPy/bin/python
libpython:      /Users/tomasz/miniconda3/envs/testPy/lib/libpython3.10.dylib
pythonhome:     /Users/tomasz/miniconda3/envs/testPy:/Users/tomasz/miniconda3/envs/testPy
version:        3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function
```

**Comment by lyndbacon** [comment]
Thanks.  From the shell:

```
lynd@zdog:~$ conda info --envs
# conda environments:
#
base                  *  /home/lynd/anaconda3
aif360                   /home/lynd/anaconda3/envs/aif360
causal                   /home/lynd/anaconda3/envs/causal
doe                      /home/lynd/anaconda3/envs/doe
gpflow2                  /home/lynd/anaconda3/envs/gpflow2
kivy                     /home/lynd/anaconda3/envs/kivy
openCV                   /home/lynd/anaconda3/envs/openCV
openDP                   /home/lynd/anaconda3/envs/openDP
py310                    /home/lynd/anaconda3/envs/py310
py38                     /home/lynd/anaconda3/envs/py38
pytorch                  /home/lynd/anaconda3/envs/pytorch
rare-events              /home/lynd/anaconda3/envs/rare-events
testPy                   /home/lynd/anaconda3/envs/testPy
tfpy38                   /home/lynd/anaconda3/envs/tfpy38
tfpy39                   /home/lynd/anaconda3/envs/tfpy39
yellowbrick              /home/lynd/anaconda3/envs/yellowbrick
```
I created the testPy conda env using:
```
lynd@zdog:~$ conda create -n testPy python=3.10
```
I do not know why reticulate is binding to /usr/bin/Python.  I have neither a .Rprofile file, or an .Renviron file anywhere on this computer.

Interestingly, If I downgrade to reticulate v=1.22, I can set RETICULATE_PYTHON to a specific conda env using SYS.setenv(), in e.g. .Rprofile, but then I can't use a current version of Keras, which expects reticulate 1.25.

**Comment by lyndbacon** [comment]
If using R and reticulate I recreate a virtualenv called r-reticulate,  relaunching R and loading reticulate defaults to that virtualenv, according to py_config().   If I create a second virtualenv, I can't switch to it using use_virtualenv().  No error message is produced. The virtualenv in use is just unchanged.   If I try to switch virtualenv to a Python virtualenv created using Python, I do get an error message, e.g.
```
> reticulate::use_virtualenv('powerlaws')
ERROR: The requested version of Python
('/home/lynd/.virtualenvs/powerlaws/bin/python') cannot be used, as
another version of Python
('/home/lynd/.virtualenvs/r-reticulate/bin/python') has already been
initialized. Please restart the R session if you need to attach
reticulate to a different version of Python.
Error in use_python(python, required = required) : 
  failed to initialize requested version of Python
```
All virtualenvs created either by  using R/reticulate, or with Python, are in the same home directory: /home/lynd/.virtualenvs

**Comment by t-kalinowski** [comment]
Once reticulate has bound to a python installation, it cannot unbind or rebind to another for the remainder of the R session. I.e., only one Python installation per R session. The solution is to start a fresh R session if you want to bind to a different Python.

**Comment by lyndbacon** [comment]
What's happening is that my R sessions bind by default to the virtualenv r-reticulate that I created.  This seems to happen as it's the first Python version reticulate fines.  As far as I can tell, there is no way to prevent this other than removing the r-reticulate virtualenv.  Then, my sessions will bind by default to my base Python environment, /usr/bin/python3, as it has previously.

**Comment by t-kalinowski** [comment]
If you can't track down what's forcing reticulate to bind from `~/.Rprofile`, you can also clone the reticulate repo, and modify `py_initialize()` in the R source code to emit `print(rlang::trace_back())` as soon as it's called, then install your local modified reticulate, e.g., with `remotes::install_local()`.

**Comment by lyndbacon** [comment]
> Something must be forcing reticulate to bind to a python session on R startup (which is not standard behavior). Perhaps `~/.Rprofile` or `R.home("etc/Rprofile.site")`, though it could be any number of places. You can try to debug it by putting this somewhere in your startup (maybe in ~/.Rprofile, though it might be too late in the startup sequence by then).
> 
> ```r
> trace(reticulate:::py_initialize, quote(print(rlang::trace_back())))
> ```
> 
> You can also look through the documentation in `?Startup` for suggestions on other places to look. Something is non-standard about your installation and you'll have to track down what that is.

Thanks.  I don't have an .Rprofile or an Rprofile.site anywhere on the computer.   I'll see what trace() can tell me.

**Comment by kevinushey** [comment]
Maybe `py_config()` could also record the call stack from when Python was initialized, so that we can introspect after the fact in cases like these?

**Comment by lyndbacon** [comment]
After inserting `

**Comment by lyndbacon** [comment]
After inserting 

`trace(reticulate:::py_initialize, quote(print(rlang::trace_back())))` in .Rprofile, and launching R, py_config() provides results:
```
> reticulate::py_config()
Tracing py_initialize(config$python, config$libpython, config$pythonhome,  .... on entry 
    ▆
 1. └─reticulate::py_config()
 2.   └─reticulate:::ensure_python_initialized()
 3.     └─reticulate:::initialize_python(required_module, use_environment)
 4.       ├─base::tryCatch(...)
 5.       │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 6.       │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7.       │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 8.       └─(function() {...
 9.         └─reticulate:::py_initialize(...)
python:         /home/lynd/.virtualenvs/r-reticulate/bin/python
libpython:      /home/lynd/.pyenv/versions/3.9.1/lib/libpython3.9.so
pythonhome:     /home/lynd/.virtualenvs/r-reticulate:/home/lynd/.virtualenvs/r-reticulate
version:        3.9.1 (default, Jul 28 2022, 15:39:15)  [GCC 9.4.0]
numpy:          /home/lynd/.virtualenvs/r-reticulate/lib/python3.9/site-packages/numpy
numpy_version:  1.23.1
[snip]
```
followed by a list of environments (virtenvs, conda), found.

**Comment by t-kalinowski** [comment]
That looks like expected behavior, `py_config()` is causing reticulate to initialize Python, (and python is uninitialized until them). Looks like the issue reported earlier in the thread is resolved?

**Comment by lyndbacon** [comment]
The original issue still exists.

If I put this in .Rprofile
`Sys.setenv(RETICULATE_PYTHON='/home/lynd/anaconda3/envs/tfpy39/bin/python')`

And then I launch R:
```
> reticulate::py_config()
/tmp/RtmpRu8EwX/file50a572b9336.sh: 5: /home/lynd/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) :
  running command ''/bin/sh' /tmp/RtmpRu8EwX/file50a572b9336.sh' had status 2
> 
```
This worked in reticulate version 1.22.

**Comment by t-kalinowski** [comment]
Some questions:

+ Are you launching R from a terminal where conda is already activated? (does your prompt start with `(base)`?
+ Is this error still present with the patch on the `conda-activate` branch? (i.e, if you install reticulate with `remotes::install_github("rstudio/reticulate@fix/conda-activate")`, do you still see the error?)
+ Please report the full output from running in terminal:
```bash
~/anaconda3/bin/conda list -n tfpy39
```
+ Please report the full output from running in terminal:
```bash
cat ~/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh
```

**Comment by lyndbacon** [comment]
Thanks.  

I have been launching R from the CLI, and not in a conda base environment.

shell script:

```
lynd@zdog:~$ cat ~/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh
#!/bin/bash

# This function takes no arguments
# It tries to determine the name of this file in a programatic way.
function _get_sourced_filename() {
    if [ -n "${BASH_SOURCE[0]}" ]; then
        basename "${BASH_SOURCE[0]}"
    elif [ -n "${(%):-%x}" ]; then
        # in zsh use prompt-style expansion to introspect the same information
        # see http://stackoverflow.com/questions/9901210/bash-source0-equivalent-in-zsh
        basename "${(%):-%x}"
    else
        echo "UNKNOWN FILE"
    fi
}

# The arguments to this are:
# 1. activation nature {activate|deactivate}
# 2. toolchain nature {build|host|ccc}
# 3. machine (should match -dumpmachine)
# 4. prefix (including any final -)
# 5+ program (or environment var comma value)
# The format for 5+ is name{,,value}. If value is specified
#  then name taken to be an environment variable, otherwise
#  it is taken to be a program. In this case, which is used
#  to find the full filename during activation. The original
#  value is stored in environment variable CONDA_BACKUP_NAME
#  For deactivation, the distinction is irrelevant as in all
#  cases NAME simply gets reset to CONDA_BACKUP_NAME.  It is
#  a fatal error if a program is identified but not present.
function _tc_activation() {
  local act_nature=$1; shift
  local tc_prefix=$1; shift
  local thing
  local newval
  local from
  local to
  local pass

  if [ "${act_nature}" = "activate" ]; then
    from=""
    to="CONDA_BACKUP_"
  else
    from="CONDA_BACKUP_"
    to=""
  fi

  for pass in check apply; do
    for thing in "$@"; do
      case "${thing}" in
        *,*)
          newval=$(echo "${thing}" | sed "s,^[^\,]*\,\(.*\),\1,")
          thing=$(echo "${thing}" | sed "s,^\([^\,]*\)\,.*,\1,")
          ;;
        *)
          newval="${CONDA_PREFIX}/bin/${tc_prefix}${thing}"
          if [ ! -x "${newval}" -a "${pass}" = "check" ]; then
            echo "ERROR: This cross-compiler package contains no program ${newval}"
            return 1
          fi
          ;;
      esac
      if [ "${pass}" = "apply" ]; then
        thing=$(echo ${thing} | tr 'a-z+-.' 'A-ZX__')
        eval oldval="\$${from}$thing"
        if [ -n "${oldval}" ]; then
          eval export "${to}'${thing}'=\"${oldval}\""
        else
          eval unset '${to}${thing}'
        fi
        if [ -n "${newval}" ]; then
          eval export "'${from}${thing}=${newval}'"
        else
          eval unset '${from}${thing}'
        fi
      fi
    done
  done
  return 0
}

if [ "${CONDA_BUILD:-0}" = "1" ]; then
  if [ -f /tmp/old-env-$$.txt ]; then
    rm -f /tmp/old-env-$$.txt || true
  fi
  env > /tmp/old-env-$$.txt
fi

# gold has not been (cannot be?) built for powerpc
if echo x86_64-conda-linux-gnu | grep powerpc > /dev/null; then
  GOLD_USED=
else
  GOLD_USED=ld.gold
fi

_tc_activation \
  activate x86_64-conda-linux-gnu- \
  addr2line ar as c++filt elfedit gprof ld ${GOLD_USED} nm objcopy objdump ranlib readelf size strings strip \

if [ $? -ne 0 ]; then
  echo "ERROR: $(_get_sourced_filename) failed, see above for details"
#exit 1
else
  if [ "${CONDA_BUILD:-0}" = "1" ]; then
    if [ -f /tmp/new-env-$$.txt ]; then
      rm -f /tmp/new-env-$$.txt || true
    fi
    env > /tmp/new-env-$$.txt

    echo "INFO: $(_get_sourced_filename) made the following environmental changes:"
    diff -U 0 -rN /tmp/old-env-$$.txt /tmp/new-env-$$.txt | tail -n +4 | grep "^-.*\|^+.*" | grep -v "CONDA_BACKUP_" | sort
    rm -f /tmp/old-env-$$.txt /tmp/new-env-$$.txt || true
  fi
fi
```
base environ activation:

```
lynd@zdog:~$ source ~/anaconda3/bin/activate
(base) lynd@zdog:~$
```
attempt to run shell script: 
```
(base) lynd@zdog:~$ sh ~/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh
/home/lynd/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: 5: Syntax error: "(" unexpected
```
The error message ends after "unexpected."

**Comment by lyndbacon** [comment]
Thanks.  

I have been launching R from the CLI, and not in a conda base environment.

shell script:

```
lynd@zdog:~$ cat ~/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh
#!/bin/bash

# This function takes no arguments
# It tries to determine the name of this file in a programatic way.
function _get_sourced_filename() {
    if [ -n "${BASH_SOURCE[0]}" ]; then
        basename "${BASH_SOURCE[0]}"
    elif [ -n "${(%):-%x}" ]; then
        # in zsh use prompt-style expansion to introspect the same information
        # see http://stackoverflow.com/questions/9901210/bash-source0-equivalent-in-zsh
        basename "${(%):-%x}"
    else
        echo "UNKNOWN FILE"
    fi
}

# The arguments to this are:
# 1. activation nature {activate|deactivate}
# 2. toolchain nature {build|host|ccc}
# 3. machine (should match -dumpmachine)
# 4. prefix (including any final -)
# 5+ program (or environment var comma value)
# The format for 5+ is name{,,value}. If value is specified
#  then name taken to be an environment variable, otherwise
#  it is taken to be a program. In this case, which is used
#  to find the full filename during activation. The original
#  value is stored in environment variable CONDA_BACKUP_NAME
#  For deactivation, the distinction is irrelevant as in all
#  cases NAME simply gets reset to CONDA_BACKUP_NAME.  It is
#  a fatal error if a program is identified but not present.
function _tc_activation() {
  local act_nature=$1; shift
  local tc_prefix=$1; shift
  local thing
  local newval
  local from
  local to
  local pass

  if [ "${act_nature}" = "activate" ]; then
    from=""
    to="CONDA_BACKUP_"
  else
    from="CONDA_BACKUP_"
    to=""
  fi

  for pass in check apply; do
    for thing in "$@"; do
      case "${thing}" in
        *,*)
          newval=$(echo "${thing}" | sed "s,^[^\,]*\,\(.*\),\1,")
          thing=$(echo "${thing}" | sed "s,^\([^\,]*\)\,.*,\1,")
          ;;
        *)
          newval="${CONDA_PREFIX}/bin/${tc_prefix}${thing}"
          if [ ! -x "${newval}" -a "${pass}" = "check" ]; then
            echo "ERROR: This cross-compiler package contains no program ${newval}"
            return 1
          fi
          ;;
      esac
      if [ "${pass}" = "apply" ]; then
        thing=$(echo ${thing} | tr 'a-z+-.' 'A-ZX__')
        eval oldval="\$${from}$thing"
        if [ -n "${oldval}" ]; then
          eval export "${to}'${thing}'=\"${oldval}\""
        else
          eval unset '${to}${thing}'
        fi
        if [ -n "${newval}" ]; then
          eval export "'${from}${thing}=${newval}'"
        else
          eval unset '${from}${thing}'
        fi
      fi
    done
  done
  return 0
}

if [ "${CONDA_BUILD:-0}" = "1" ]; then
  if [ -f /tmp/old-env-$$.txt ]; then
    rm -f /tmp/old-env-$$.txt || true
  fi
  env > /tmp/old-env-$$.txt
fi

# gold has not been (cannot be?) built for powerpc
if echo x86_64-conda-linux-gnu | grep powerpc > /dev/null; then
  GOLD_USED=
else
  GOLD_USED=ld.gold
fi

_tc_activation \
  activate x86_64-conda-linux-gnu- \
  addr2line ar as c++filt elfedit gprof ld ${GOLD_USED} nm objcopy objdump ranlib readelf size strings strip \

if [ $? -ne 0 ]; then
  echo "ERROR: $(_get_sourced_filename) failed, see above for details"
#exit 1
else
  if [ "${CONDA_BUILD:-0}" = "1" ]; then
    if [ -f /tmp/new-env-$$.txt ]; then
      rm -f /tmp/new-env-$$.txt || true
    fi
    env > /tmp/new-env-$$.txt

    echo "INFO: $(_get_sourced_filename) made the following environmental changes:"
    diff -U 0 -rN /tmp/old-env-$$.txt /tmp/new-env-$$.txt | tail -n +4 | grep "^-.*\|^+.*" | grep -v "CONDA_BACKUP_" | sort
    rm -f /tmp/old-env-$$.txt /tmp/new-env-$$.txt || true
  fi
fi
```
base environ activation:

```
lynd@zdog:~$ source ~/anaconda3/bin/activate
(base) lynd@zdog:~$
```
attempt to run shell script: 
```
(base) lynd@zdog:~$ sh ~/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh
/home/lynd/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: 5: Syntax error: "(" unexpected
```
The error message ends after "unexpected."

**Comment by t-kalinowski** [comment]
Can you please answer questions in bullets 2 and 3 in my previous comment?

**Comment by lyndbacon** [comment]
Sure.  I got the error when I tried the patch on the conda-activate branch.

```
lynd@zdog:~$ ~/anaconda3/bin/conda list
# packages in environment at /home/lynd/anaconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
aiohttp                   3.8.1            py37h540881e_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anaconda-navigator        2.2.0            py37h06a4308_0  
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
assertpy                  1.1                pyh9f0ad1d_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
asynctest                 0.13.0                     py_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       pyhd8ed1ab_1003    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_33    conda-forge
blas                      1.0                         mkl  
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
brotlipy                  0.7.0           py37h540881e_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15        py37h89c1867_0    conda-forge
cffi                      1.15.0           py37h036bc23_0    conda-forge
chardet                   5.0.0            py37h89c1867_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
clikit                    0.6.2              pyh9f0ad1d_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
cmdstan                   2.28.2               h6405898_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     4.13.0           py37h89c1867_1    conda-forge
conda-content-trust       0.1.3              pyhd8ed1ab_0    conda-forge
conda-env                 2.6.0                         1  
conda-package-handling    1.8.1            py37h540881e_1    conda-forge
conda-repo-cli            1.0.4              pyhd3eb1b0_0  
conda-suggest             0.1.1              pyh9f0ad1d_0    conda-forge
conda-suggest-conda-forge 2021.8.24            ha770c72_0    conda-forge
conda-token               0.3.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
crashtest                 0.3.1              pyhd8ed1ab_0    conda-forge
cryptography              37.0.2           py37h38fbfac_0    conda-forge
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
datatable                 0.11.1           py37h6dcda5c_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
fastapi                   0.62.0             pyhd8ed1ab_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonttools                 4.33.3           py37h540881e_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.3.0            py37h540881e_1    conda-forge
future                    0.18.2           py37h89c1867_5    conda-forge
gcc_impl_linux-64         9.3.0               h6df7d76_17  
gcc_linux-64              9.3.0               hf25ea35_33    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
glib                      2.70.2               h780b84a_4    conda-forge
glib-tools                2.70.2               h780b84a_4    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               h28cd5cc_2  
gxx_impl_linux-64         9.3.0               hbdd7822_17  
gxx_linux-64              9.3.0               h3fbe746_33    conda-forge
gym                       0.18.0                    dev_0    <develop>
hdf5                      1.10.6               hb1b8bf9_0  
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
httpstan                  4.5.0            py37h2527ec5_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py37h89c1867_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.33.0           py37h89c1867_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py37h89c1867_2    conda-forge
jinja2                    2.11.3             pyhd3eb1b0_0  
jpeg                      9e                   h166bdaf_2    conda-forge
jsonschema                3.2.0                      py_2  
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.10.0           py37h89c1867_0    conda-forge
jupyterthemes             0.20.0                     py_1    conda-forge
keepalive                 0.5                pyhd8ed1ab_6    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.3            py37h7cecad7_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
langdetect                1.0.8              pyh9f0ad1d_0    conda-forge
lazygit                   0.32.2               ha770c72_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
lesscpy                   0.15.0             pyhd8ed1ab_0    conda-forge
libarchive                3.5.2                hb890918_3    conda-forge
libblas                   3.9.0           1_h6e990d7_netlib    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           3_h893e4fe_netlib    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdeflate                1.12                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     9.3.0               hb95220a_17  
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           3_h893e4fe_netlib    conda-forge
libmamba                  0.25.0               hd8a31e3_1    conda-forge
libmambapy                0.25.0           py37h1ee4b26_1    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.22               h6239696_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-devel_linux-64  9.3.0               hf0c5c8d_17  
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                hc85c160_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h74e7548_0  
libzlib                   1.2.12               h166bdaf_1    conda-forge
lime                      0.2.0.1            pyh9f0ad1d_0    conda-forge
litereval                 0.0.11                     py_0    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
lz4                       4.0.0            py37hbaff0ff_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
mamba                     0.25.0           py37h6dacc13_1    conda-forge
markdown                  3.3.4            py37h06a4308_0  
markupsafe                2.0.1            py37h5e8e339_1    conda-forge
marshmallow               3.17.0             pyhd8ed1ab_0    conda-forge
matplotlib                3.5.1            py37h89c1867_0    conda-forge
matplotlib-base           3.5.1            py37h1058ff1_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mkl                       2020.0                      166    conda-forge
more-itertools            8.10.0             pyhd8ed1ab_0    conda-forge
multidict                 6.0.2            py37h540881e_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
murmurhash                1.0.5            py37h2531618_0  
navigator-updater         0.2.1                    py37_0  
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
neo4j-python-driver       4.3.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
numpy                     1.19.5           py37h038b26d_2    conda-forge
openblas                  0.3.4             h9ac9557_1000    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandoc                    2.11.3.1             h7f98852_0    conda-forge
parso                     0.7.0                      py_0  
pastel                    0.2.1              pyhd8ed1ab_0    conda-forge
pathlib                   1.0.1                    py37_1  
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.1            py37h44f0d7a_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pipe                      2.0                pyhd8ed1ab_0    conda-forge
plotly                    5.6.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
prompt_toolkit            3.0.30               hd8ed1ab_0    conda-forge
psutil                    5.9.1            py37h540881e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py37h540881e_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.8.2            py37h5e8e339_2    conda-forge
pydash                    5.0.1              pyh6c4a22f_0    conda-forge
pyee                      8.1.0              pyhd8ed1ab_0    conda-forge
pyforest                  0.1.2                    py37_0    a8080labs
pyglet                    1.5.15                   pypi_0    pypi
pygments                  2.7.3              pyhd3eb1b0_0  
pyjwt                     2.4.0              pyhd8ed1ab_0    conda-forge
pylev                     1.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppdf                    0.1.2                      py_0    conda-forge
pyppeteer                 1.0.2              pyhd8ed1ab_0    conda-forge
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.18.1           py37h540881e_1    conda-forge
pysimdjson                5.0.1            py37hd23a5d3_0    conda-forge
pysocks                   1.7.1            py37h89c1867_5    conda-forge
pystan                    3.2.0            py37h796e4cb_0    conda-forge
python                    3.7.12          hb7a2778_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py37h540881e_4    conda-forge
pyzmq                     23.2.0           py37h0c0c2a8_0    conda-forge
qt                        5.9.7                h5867ecd_1  
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
rdflib                    5.0.0            py37hc8dfbb8_2    conda-forge
re2                       2020.10.01           he1b5a44_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
regex                     2022.1.18        py37h5e8e339_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py37h540881e_1007    conda-forge
setproctitle              1.1.10          py37h7b6447c_1001  
setuptools                47.1.1                   py37_0  
shellingham               1.4.0              pyh44b312d_0    conda-forge
simplejson                3.17.2           py37h7b6447c_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sparqlwrapper             1.8.5           py37h89c1867_1006    conda-forge
sqlite                    3.39.0               h4ff8645_0    conda-forge
starlette-base            0.13.6                     py_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tabulate                  0.8.7                    py37_0  
tbb                       2021.5.0             h924138e_1    conda-forge
tbb-devel                 2021.5.0             h924138e_1    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1              py37h540881e_3    conda-forge
tqdm                      4.51.0             pyh9f0ad1d_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typer                     0.4.0              pyhd8ed1ab_0    conda-forge
typing-extensions         3.10.0.2             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
ujson                     5.3.0            py37hd23a5d3_0    conda-forge
unicodedata2              14.0.0           py37h540881e_1    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webargs                   8.1.0              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websockets                10.3             py37h540881e_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xonsh                     0.12.2           py37h89c1867_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xxh-xxh                   0.8.6              pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_1    conda-forge
yarl                      1.7.2            py37h540881e_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_1    conda-forge
zstd                      1.5.2                h8a70e8d_2    conda-forge
lynd@zdog:~$ 

```

**Comment by t-kalinowski** [comment]
> I got the error when I tried the patch on the conda-activate branch.

What error is that? Can you please show the full output of running this in terminal: 
```
Rscript -e 'remotes::install_github("rstudio/reticulate@fix/conda-activate")'
RETICULATE_PYTHON=~/anaconda3/envs/tfpy39/bin/python Rscript -e 'reticulate::py_config()'
```

**Comment by lyndbacon** [comment]
Well, I remembered incorrectly exactly what happened when I installed the patch. Sorry about that. I got an installation, as follows. 

```
ynd@zdog:~$ Rscript -e 'remotes::install_github("rstudio/reticulate@fix/conda-activate")'
Downloading GitHub repo rstudio/reticulate@fix/conda-activate

✔  checking for file ‘/tmp/RtmpN822he/remotesde6513cbb01c/rstudio-reticulate-ad7d563/DESCRIPTION’ ...
─  preparing ‘reticulate’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘reticulate_1.25-9000.tar.gz’
   
Installing package into ‘/home/lynd/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package ‘reticulate’ ...
** using staged installation
** libs
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -O3 -pipe      -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -O3 -pipe      -c event_loop.cpp -o event_loop.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -O3 -pipe      -c libpython.cpp -o libpython.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -O3 -pipe      -c output.cpp -o output.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -O3 -pipe      -c python.cpp -o python.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -O3 -pipe      -c readline.cpp -o readline.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -O3 -pipe      -c signals.cpp -o signals.o
g++ -std=gnu++14 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o reticulate.so RcppExports.o event_loop.o libpython.o output.o python.o readline.o signals.o -L/usr/lib/R/lib -lR
installing to /home/lynd/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-reticulate/00new/reticulate/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (reticulate)
Warning messages:
1: In readLines(old_path) :
  incomplete final line found on '/home/lynd/.R/Makevars'
2: In readLines(old_path) :
  incomplete final line found on '/home/lynd/.R/Makevars'
lynd@zdog:~$ 

```

**Comment by lyndbacon** [comment]
So, this part, after having reinstalled the patch:

```
lynd@zdog:~$ RETICULATE_PYTHON=~/anaconda3/envs/tfpy39/bin/python Rscript -e 'reticulate::py_config()'
python:         /home/lynd/anaconda3/envs/tfpy39/bin/python
libpython:      /home/lynd/anaconda3/envs/tfpy39/lib/libpython3.9.so
pythonhome:     /home/lynd/anaconda3/envs/tfpy39:/home/lynd/anaconda3/envs/tfpy39
version:        3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21)  [GCC 10.3.0]
numpy:          /home/lynd/anaconda3/envs/tfpy39/lib/python3.9/site-packages/numpy
numpy_version:  1.22.4
```

**Comment by t-kalinowski** [comment]
Looks like everything works! I'll merge the patch and close the issue.

**Comment by lyndbacon** [comment]
> Looks like everything works! I'll merge the patch and close the issue.

It does!  Thanks for your help with this.  I didn't fully use the patch previously because I was concerned about the warning messages.
