### ISSUE TITLE
Neither install_python(), nor miniconda_install() work in Win11 now.

### ISSUE THREAD

**Issue by erdeyl** [rstudio/reticulate#1286]
The first runs to an error looking for a nonexistent library, the second keeps trying to find an openssl connection. Any advice, please?

**Comment by kevinushey** [comment]
Can you please share the actual error messages you are seeing?

**Comment by erdeyl** [comment]
Sure, I should have started with this. Windows 11 Pro, 22H2,Rstudio  2022.07.2 Build 576, R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid". All packages are updated.
> library(reticulate)
> install_python()
Error in setwd(root) : cannot change working directory
------------------------------------------------------------------------


> library(reticulate)
> library(openssl) # I have without and with this

.......
+ "C:/Users/erdey/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--name" "r-reticulate" "python=3.8" "numpy" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... failed

CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
download and install packages.

Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))


Error: Error creating conda environment 'r-reticulate' [exit code 1]

**Comment by t-kalinowski** [comment]
I can reproduce the error with `install_miniconda()` on Windows 10, but `install_python()` succeeds without issue for me. 
<details>
  <summary> <code>install_miniconda()</code> </summary>

```cmd
> reticulate::install_miniconda()
* Installing Miniconda -- please wait a moment ...
* Downloading "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe" ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe'
Content type 'application/octet-stream' length 74687656 bytes (71.2 MB)
downloaded 71.2 MB

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\kalin\AppData\Local\R-MINI~1

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.07.19 |       haa95532_0         123 KB
    certifi-2022.9.24          |   py39haa95532_0         154 KB
    cffi-1.15.1                |   py39h2bbff1b_0         218 KB
    colorama-0.4.5             |   py39haa95532_0          28 KB
    conda-22.9.0               |   py39haa95532_0         888 KB
    conda-package-handling-1.9.0|   py39h8cc25b3_0         726 KB
    cryptography-37.0.1        |   py39h21b164f_0         977 KB
    openssl-1.1.1q             |       h2bbff1b_0         4.8 MB
    pip-22.2.2                 |   py39haa95532_0         2.3 MB
    requests-2.28.1            |   py39haa95532_0          99 KB
    setuptools-63.4.1          |   py39haa95532_0         1.0 MB
    sqlite-3.39.3              |       h2bbff1b_0         804 KB
    toolz-0.11.2               |     pyhd3eb1b0_0          49 KB
    tqdm-4.64.1                |   py39haa95532_0         143 KB
    tzdata-2022c               |       h04d1e81_0         107 KB
    urllib3-1.26.11            |   py39haa95532_0         184 KB
    ------------------------------------------------------------
                                           Total:        12.6 MB

The following NEW packages will be INSTALLED:

  toolz              pkgs/main/noarch::toolz-0.11.2-pyhd3eb1b0_0

The following packages will be REMOVED:

  conda-content-trust-0.1.1-pyhd3eb1b0_0
  six-1.16.0-pyhd3eb1b0_1

The following packages will be UPDATED:

  ca-certificates                      2022.3.29-haa95532_1 --> 2022.07.19-haa95532_0
  certifi                          2021.10.8-py39haa95532_2 --> 2022.9.24-py39haa95532_0
  cffi                                1.15.0-py39h2bbff1b_1 --> 1.15.1-py39h2bbff1b_0
  colorama           pkgs/main/noarch::colorama-0.4.4-pyhd~ --> pkgs/main/win-64::colorama-0.4.5-py39haa95532_0
  conda                               4.12.0-py39haa95532_0 --> 22.9.0-py39haa95532_0
  conda-package-han~                   1.8.1-py39h8cc25b3_0 --> 1.9.0-py39h8cc25b3_0
  cryptography                        36.0.0-py39h21b164f_0 --> 37.0.1-py39h21b164f_0
  openssl                                 1.1.1n-h2bbff1b_0 --> 1.1.1q-h2bbff1b_0
  pip                                 21.2.4-py39haa95532_0 --> 22.2.2-py39haa95532_0
  requests           pkgs/main/noarch::requests-2.27.1-pyh~ --> pkgs/main/win-64::requests-2.28.1-py39haa95532_0
  setuptools                          61.2.0-py39haa95532_0 --> 63.4.1-py39haa95532_0
  sqlite                                  3.38.2-h2bbff1b_0 --> 3.39.3-h2bbff1b_0
  tqdm               pkgs/main/noarch::tqdm-4.63.0-pyhd3eb~ --> pkgs/main/win-64::tqdm-4.64.1-py39haa95532_0
  tzdata                                   2022a-hda174b7_0 --> 2022c-h04d1e81_0
  urllib3            pkgs/main/noarch::urllib3-1.26.8-pyhd~ --> pkgs/main/win-64::urllib3-1.26.11-py39haa95532_0



Downloading and Extracting Packages
openssl-1.1.1q       | 4.8 MB    | ########## | 100% 
requests-2.28.1      | 99 KB     | ########## | 100% 
ca-certificates-2022 | 123 KB    | ########## | 100% 
colorama-0.4.5       | 28 KB     | ########## | 100% 
certifi-2022.9.24    | 154 KB    | ########## | 100% 
tzdata-2022c         | 107 KB    | ########## | 100% 
setuptools-63.4.1    | 1.0 MB    | ########## | 100% 
tqdm-4.64.1          | 143 KB    | ########## | 100% 
conda-22.9.0         | 888 KB    | ########## | 100% 
pip-22.2.2           | 2.3 MB    | ########## | 100% 
cffi-1.15.1          | 218 KB    | ########## | 100% 
toolz-0.11.2         | 49 KB     | ########## | 100% 
cryptography-37.0.1  | 977 KB    | ########## | 100% 
sqlite-3.39.3        | 804 KB    | ########## | 100% 
urllib3-1.26.11      | 184 KB    | ########## | 100% 
conda-package-handli | 726 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ "C:/Users/kalin/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--name" "r-reticulate" "python=3.8" "numpy" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... failed

CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
download and install packages.

Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))


Error: Error creating conda environment 'r-reticulate' [exit code 1]
```
</details>


<details>
  <summary> <code>install_python()</code></summary>

``` cmd
> reticulate::install_python()
Cloning into 'C:/Users/kalin/AppData/Local/r-reticulate/r-reticulate/pyenv'...
Already up to date.
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Info] ::  Scanned 181 pages and found 577 installers.
+ "C:/Users/kalin/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/bin/pyenv" install 3.9.13
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Downloading] ::  3.9.13 ...
:: [Downloading] ::  From https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe
:: [Downloading] ::  To   C:\Users\kalin\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\install_cache\python-3.9.13-amd64.exe
:: [Installing] ::  3.9.13 ...
:: [Info] :: completed! 3.9.13
[1] "C:/Users/kalin/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python.exe"

> reticulate::virtualenv_create("r-reticulate", reticulate::install_python())
+ "C:/Users/kalin/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/bin/pyenv" install 3.9.13
:: [Info] ::  Mirror: https://www.python.org/ftp/python
Using Python: C:/Users/kalin/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python.exe
Creating virtual environment "r-reticulate" ... 
+ "C:/Users/kalin/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python.exe" -m venv "C:/Users/kalin/Documents/.virtualenvs/r-reticulate"
Done!
Installing packages: "pip", "wheel", "setuptools", "numpy"
+ "C:/Users/kalin/Documents/.virtualenvs/r-reticulate/Scripts/python.exe" -m pip install --upgrade --no-user "pip" "wheel" "setuptools" "numpy"
Requirement already satisfied: pip in c:\users\kalin\documents\.virtualenvs\r-reticulate\lib\site-packages (22.0.4)
Collecting pip
  Using cached pip-22.2.2-py3-none-any.whl (2.0 MB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Requirement already satisfied: setuptools in c:\users\kalin\documents\.virtualenvs\r-reticulate\lib\site-packages (58.1.0)
Collecting setuptools
  Using cached setuptools-65.4.1-py3-none-any.whl (1.2 MB)
Collecting numpy
  Downloading numpy-1.23.4-cp39-cp39-win_amd64.whl (14.7 MB)
     --------------------------------------- 14.7/14.7 MB 16.8 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools, pip, numpy
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed numpy-1.23.4 pip-22.2.2 setuptools-65.4.1 wheel-0.37.1
Virtual environment 'r-reticulate' successfully created.
> keras::install_keras(envname = "r-reticulate")
Using virtual environment "r-reticulate" ...
+ "C:/Users/kalin/Documents/.virtualenvs/r-reticulate/Scripts/python.exe" -m pip install --upgrade --no-user --ignore-installed "tensorflow==2.9.*" "tensorflow-hub" "scipy" "requests" "Pillow" "h5py" "pandas" "pydot"
Collecting tensorflow==2.9.*
  Downloading tensorflow-2.9.2-cp39-cp39-win_amd64.whl (444.1 MB)
     -------------------------------------- 444.1/444.1 MB 5.5 MB/s eta 0:00:00
Collecting tensorflow-hub
  Using cached tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
Collecting scipy
  Downloading scipy-1.9.2-cp39-cp39-win_amd64.whl (40.1 MB)
     --------------------------------------- 40.1/40.1 MB 26.2 MB/s eta 0:00:00
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting Pillow
  Using cached Pillow-9.2.0-cp39-cp39-win_amd64.whl (3.3 MB)
Collecting h5py
  Downloading h5py-3.7.0-cp39-cp39-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 33.6 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-1.5.0-cp39-cp39-win_amd64.whl (10.9 MB)
     --------------------------------------- 10.9/10.9 MB 28.5 MB/s eta 0:00:00
Collecting pydot
  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting termcolor>=1.1.0
  Downloading termcolor-2.0.1-py3-none-any.whl (5.4 kB)
Collecting absl-py>=1.0.0
  Using cached absl_py-1.2.0-py3-none-any.whl (123 kB)
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting protobuf<3.20,>=3.9.2
  Using cached protobuf-3.19.6-cp39-cp39-win_amd64.whl (895 kB)
Collecting typing-extensions>=3.6.6
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting numpy>=1.20
  Using cached numpy-1.23.4-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting gast<=0.4.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting flatbuffers<2,>=1.12
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting grpcio<2.0,>=1.24.3
  Using cached grpcio-1.49.1-cp39-cp39-win_amd64.whl (3.6 MB)
Collecting setuptools
  Using cached setuptools-65.4.1-py3-none-any.whl (1.2 MB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.27.0-cp39-cp39-win_amd64.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 31.4 MB/s eta 0:00:00
Collecting wrapt>=1.11.0
  Using cached wrapt-1.14.1-cp39-cp39-win_amd64.whl (35 kB)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting tensorboard<2.10,>=2.9
  Using cached tensorboard-2.9.1-py3-none-any.whl (5.8 MB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting six>=1.12.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting keras-preprocessing>=1.1.1
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting tensorflow-estimator<2.10.0,>=2.9.0rc0
  Using cached tensorflow_estimator-2.9.0-py2.py3-none-any.whl (438 kB)
Collecting libclang>=13.0.0
  Downloading libclang-14.0.6-py2.py3-none-win_amd64.whl (14.2 MB)
     --------------------------------------- 14.2/14.2 MB 26.2 MB/s eta 0:00:00
Collecting keras<2.10.0,>=2.9.0rc0
  Using cached keras-2.9.0-py2.py3-none-any.whl (1.6 MB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1
  Downloading pytz-2022.4-py2.py3-none-any.whl (500 kB)
     ------------------------------------- 500.8/500.8 kB 32.7 MB/s eta 0:00:00
Collecting pyparsing>=2.1.4
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting wheel<1.0,>=0.23.0
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting werkzeug>=1.0.1
  Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.12.0-py2.py3-none-any.whl (169 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata>=4.4
  Using cached importlib_metadata-5.0.0-py3-none-any.whl (21 kB)
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.1-cp39-cp39-win_amd64.whl (17 kB)
Collecting zipp>=0.5
  Downloading zipp-3.9.0-py3-none-any.whl (5.8 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.1-py3-none-any.whl (151 kB)
Installing collected packages: tensorboard-plugin-wit, pytz, pyasn1, libclang, keras, flatbuffers, zipp, wrapt, wheel, urllib3, typing-extensions, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, six, setuptools, rsa, pyparsing, pyasn1-modules, protobuf, Pillow, oauthlib, numpy, MarkupSafe, idna, gast, charset-normalizer, certifi, cachetools, absl-py, werkzeug, tensorflow-hub, scipy, requests, python-dateutil, pydot, packaging, opt-einsum, keras-preprocessing, importlib-metadata, h5py, grpcio, google-pasta, google-auth, astunparse, requests-oauthlib, pandas, markdown, google-auth-oauthlib, tensorboard, tensorflow
Successfully installed MarkupSafe-2.1.1 Pillow-9.2.0 absl-py-1.2.0 astunparse-1.6.3 cachetools-5.2.0 certifi-2022.9.24 charset-normalizer-2.1.1 flatbuffers-1.12 gast-0.4.0 google-auth-2.12.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.49.1 h5py-3.7.0 idna-3.4 importlib-metadata-5.0.0 keras-2.9.0 keras-preprocessing-1.1.2 libclang-14.0.6 markdown-3.4.1 numpy-1.23.4 oauthlib-3.2.1 opt-einsum-3.3.0 packaging-21.3 pandas-1.5.0 protobuf-3.19.6 pyasn1-0.4.8 pyasn1-modules-0.2.8 pydot-1.4.2 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.4 requests-2.28.1 requests-oauthlib-1.3.1 rsa-4.9 scipy-1.9.2 setuptools-65.4.1 six-1.16.0 tensorboard-2.9.1 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.9.2 tensorflow-estimator-2.9.0 tensorflow-hub-0.12.0 tensorflow-io-gcs-filesystem-0.27.0 termcolor-2.0.1 typing-extensions-4.4.0 urllib3-1.26.12 werkzeug-2.2.2 wheel-0.37.1 wrapt-1.14.1 zipp-3.9.0

Installation complete.

Restarting R session...

> library(tensorflow)
> use_virtualenv("r-reticulate")
Loaded Tensorflow version 2.9.2
> tf$abs(3)
tf.Tensor(3.0, shape=(), dtype=float32)
```
</details>

**Comment by t-kalinowski** [comment]
There is an active thread about this here: https://github.com/conda/conda/issues/11795. It looks like the fix is to do some additional path munging.

**Comment by erdeyl** [comment]
Thank you very much for your efforts. 
To be sure, I have tried install_python() on two different laptops (Win10, Win11); the errors came up on both, even when I tried from R GUI with admin role and Rstudio. I cannot imagine what the problem is.

**Comment by erdeyl** [comment]
> There is an active thread about this here: [conda/conda#11795](https://github.com/conda/conda/issues/11795). It looks like the fix is to do some additional path munging.

Oh, I see, I will read it trough soon. Thank you very much.

**Comment by kevinushey** [comment]
`options(error = recover)` would probably help us diagnose your `install_python()` issue, but it's most likely coming from these places:

https://github.com/rstudio/reticulate/blob/b14e7ca085998aaa15bb0932c3ba3874a3838c80/R/pipenv.R#L36
https://github.com/rstudio/reticulate/blob/b14e7ca085998aaa15bb0932c3ba3874a3838c80/R/pyenv.R#L179

**Comment by t-kalinowski** [comment]
I have a fix in the works. We needs to prepend `CONDA_PREFIX/Library/bin` and a few other locations to PATH before calling the `conda` (and miniconda) binary. I have meetings most of the afternoon, but I'll try to push before the end of the day.

**Comment by erdeyl** [comment]
You are great. I realky appreciate the great work you do.

**Comment by t-kalinowski** [comment]
@erdeyl I just pushed a fix for `install_miniconda()`. Can you please install the dev version of reticulate and try again?

**Comment by erdeyl** [comment]
install_miniconda() works like a charm in the dev version. Thank you very much!
install_python() still drops the same error message, but I can live with it.
I appreciate your fast a careful reaction.

**Comment by barryrowlingson** [comment]
Am I right in thinking this hasn't been pushed to CRAN yet? I'm still seeing errors related to OpenSSL and conda using reticulate 1.26 from CRAN and it looks like the functions don't have the changes in the commit so I'm guessing its not on CRAN yet. Any timeline for that?
