### ISSUE TITLE
error when using reticulate in Rmarkdown

### ISSUE THREAD

**Issue by HediaTnani** [rstudio/reticulate#831]
Hi,

I'm having this error `Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: use() got an unexpected keyword argument 'warn'` when running this code in Rmarkdown
```{python}
#Import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_table('../../data.txt',sep='\t',header=(0))
df.describe()
```

I'm running this chunk before:
```{r}
library(reticulate)
use_python("/usr/bin/python")
```
How to solve this error message please?

**Comment by kevinushey** [comment]
This is an issue that should be fixed in the development version of `reticulate` -- can you try upgrading with:

```
remotes::install_github("rstudio/reticulate")
```

**Comment by pinogl** [comment]
Hi,
I had the same issue and the upgrade with the development fixed it.
Thank you

**Comment by BhuvaneshMurugan** [comment]
Even though After installing the Latest version of Reticulate, the  error still apperars

**Comment by kevinushey** [comment]
This most likely depends on the version of matplotlib that is installed. This is where we call `use()`:

https://github.com/rstudio/reticulate/blob/e7a311178a5fbe97ee0d073bab0d54fee173120f/R/knitr-engine.R#L396-L400

@BhuvaneshMurugan, what version of `matplotlib` do you have installed? Does updating to the latest version resolve things?

**Comment by pvsundar** [comment]
> Even though After installing the Latest version of Reticulate, the error still apperars

i have the same issue. i am using RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-14) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
 **I am using python 3.11.7**
I have reinstalled the latest "reticulate" using:
remotes::install_github("rstudio/reticulate")
--------------------
Error in `py_call_impl()`:
! NameError: name 'warnings' is not defined
Run `reticulate::py_last_error()` for details.
Backtrace:
  1. rmarkdown::render(...)
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  8. knitr:::process_group.block(group)
  9. knitr:::call_block(x)
     ...
 13. knitr (local) engine(options)
 14. reticulate::eng_python(options)
 15. reticulate:::py_compile_eval(snippet, compile_mode)
 18. builtins$eval(compiled, globals, locals)
 19. reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)

**Comment by t-kalinowski** [comment]
Hi @pvsundar the error message you're seeing is a little different, and likely unrelated to the original issue (which is fixed already). Can you please open a new issue, ideally with a minimal reproducible example that generates the error?
